name: 'Olá mundo, action'
description: 'Olá mundo, action evento new push'
author: 'Silas Oliveira'

inputs:
  source:
    required: true
    type: string
    description: Lista de Arquivos para copiar
  target:
    required: true
    type: string
    description: Diretório de desinto do Servidor
  run_number:
    required: true
  github_token:
    required: true
    type: string

runs:
  using: 'node12'
  main: 'dist/index.js'